// Auto-generated by make_fonts.py — do not edit.
#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct { uint16_t off; uint8_t w, h; int8_t xoff, yoff; uint8_t adv; } sig_glyph_t;
typedef struct { uint8_t fam; int16_t wt; float px; int16_t ascent, descent, gap;
  uint16_t n; const char* chars; const sig_glyph_t* gl; const uint8_t* bmp; uint32_t bmplen; } sig_font_t;
enum { FAM_DISP=0, FAM_MONO=1, FAM_SERIF=2 };
#ifdef __cplusplus
}
#endif
#define F_DISP_500_15 0
#define F_DISP_600_14_5 1
#define F_DISP_600_15 2
#define F_DISP_600_15_5 3
#define F_DISP_600_16 4
#define F_DISP_700_21 5
#define F_DISP_700_22 6
#define F_DISP_800_36 7
#define F_DISP_800_46 8
#define F_DISP_800_96 9
#define F_MONO_400_9 10
#define F_MONO_400_9_5 11
#define F_MONO_400_10 12
#define F_MONO_400_10_5 13
#define F_MONO_400_11 14
#define F_MONO_400_11_5 15
#define F_MONO_400_12 16
#define F_MONO_400_16 17
#define F_MONO_500_10_5 18
#define F_MONO_500_11 19
#define F_MONO_500_12 20
#define F_MONO_500_13 21
#define F_MONO_600_7_5 22
#define F_MONO_600_8_5 23
#define F_MONO_600_10_5 24
#define F_MONO_600_11 25
#define F_MONO_600_11_5 26
#define F_MONO_600_13_5 27
#define F_MONO_600_15 28
#define F_MONO_600_60 29
#define F_SERIF_400_22 30
